logging:
  level:
    de.flowsuite.mailflow: INFO
    org.springframework.security: INFO

mailflow:
  frontend:
    url: https://dashboard.mail-flow.com
  api:
    base-url: https://api.mail-flow.com/api/v1
