spring:
  application:
    name: MailFlow-API
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.ionos.de
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /api/v1

logging:
  level:
    de.flowsuite.mailflowapi: DEBUG
    org.springframework.security: TRACE

google:
  recaptcha:
    http-header: reCAPTCHA
    secret-key: ${GOOGLE_RECAPTCHA_SECRET_KEY}
    verify-url: https://www.google.com/recaptcha/api/siteverify
    threshold: 0.5
