spring:
  application:
    name: mailflow-api
  profiles:
    active: ${ACTIVE_PROFILE}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
  jackson:
    time-zone: Europe/Berlin
  mail:
    host: smtp.ionos.de
    port: 465
    username: info@flow-suite.de
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /api/v1

google:
  recaptcha:
    http-header: reCAPTCHA
    secret-key: ${GOOGLE_RECAPTCHA_SECRET_KEY}
    verify-url: https://www.google.com/recaptcha/api/siteverify
    threshold: 0.5