spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
  jackson:
    time-zone: Europe/Berlin
  mail:
    host: smtp.ionos.de
    port: 465
    username: info@flow-suite.de
    password: mocked
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /api/v1

google:
  recaptcha:
    http-header: reCAPTCHA
    secret-key: mocked
    verify-url: https://www.google.com/recaptcha/api/siteverify
    threshold: 0.5

client:
  name: mocked
  secret: mocked